### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by glynnw** [jodylecompte/AdLinkr#1]
I'm working on adding linting for consistency like you and I discussed however I had some questions.
Do you want me to go ahead and clean up the linting errors?
Also do you want the es6 globals like Set, WeakMap, etc?

**Comment by jodylecompte** [comment]
Hey @glynnw,

That sounds fine. I'm not sure what the significance of the ES6 globals is, does that just mean eslint won't throw errors for using them?

**Comment by glynnw** [comment]
Yeah it won't throw errors for using them. Lets eslint know to expect or not to expect them.
