### ISSUE TITLE
yarn test fails in Windows with Git Bash - export not available

### ISSUE THREAD

**Issue by rricheydev** [jodylecompte/AdLinkr#5]
Clean fork / clone / install (for both root and frontend)

Terminal Error Output

```
$ yarn test
yarn run v1.6.0
$ export NODE_ENV=dev || SET NODE_ENV=dev && mocha ./tests/**/test_*.js && mocha ./tests/**/**/test_*.js
'export' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by glynnw** [comment]
https://github.com/kentcdodds/cross-env is something to consider. Or maybe there is some other way to fix this without pulling in that package.

**Comment by jodylecompte** [comment]
@rricheydev Thanks for letting me know, I'll take a look later this evening and see how the environmental variables need to be handled. 

@glynnw cross-env will likely be the way to go. A quick google search of solutions addressing this without cross-env seemed to be a little on the nastier side.

**Comment by jodylecompte** [comment]
For the short term, I just brought in cross-env to fix this library and verified that test suite was running properly in PowerShell, GitBash, and Command Prompt under Windows 10.

Will re-visit after release of 0.1 and ensure that Windows support is first class. Thanks again for letting me know @rricheydev.
